#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Karun Japhet <karun@japhet.in>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Exported variables
export HISTCONTROL=$HISTCONTROL:ignorespace
export JAVA_HOME=$(/usr/libexec/java_home)
export GOPATH="$HOME/.go"
export PATH="$PATH:$HOME/.go/bin"
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH=$PATH:$JAVA_HOME/bin
export PATH="/usr/local/opt/gpg-agent/bin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export HOMEBREW_GITHUB_API_TOKEN="1b4ebac3c6a9178cc62b389a5e25078d8ff5cb54"

# Profile Editing aliases
alias epro="vi ~/.zshrc && . ~/.zshrc"
alias rpro="source ~/.zshrc"

alias gs="git status"
alias gd="git diff"
alias ga="git add"
alias pull="git pull -r"
alias push="git push"
alias reset="git reset --hard HEAD"

alias l="ls -l"
alias g=./gradlew
alias rmd="rm -rf"

alias vi="vim"

alias json="cat $1 | jq ."
alias dc="docker-compose"

# Auto jump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# The Fuck: Command fix alias
eval $(thefuck --alias --enable-experimental-instant-mode)

# Autogenerated

# added by travis gem
[ -f /Users/karun/.travis/travis.sh ] && source /Users/karun/.travis/travis.sh
